spring:
  cloud:
    stream:
      bindings:
        user-master-channel:
          destination: user-master
        user-login-channel:
          destination: user-login
      kafka:
        streams:
          binder:
            brokers:  localhost:9092
            configuration:
              commit.interval.ms: 10000
              state.dir: state-store
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde

