spring:
  cloud:
    stream:
      bindings:
        xml-input-channel:
          destination: xml-order-topic
        india-orders-channel:
          destination: india-orders
        abroad-orders-channel:
          destination: abroad-orders
      kafka:
        streams:
          binder:
            brokers:  localhost:9092
            configuration:
              schema.registry.url: http://localhost:8081
              processing.guarantee: exactly_once
          bindings:
            india-orders-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.json.KafkaJsonSchemaSerde
            abroad-orders-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.json.KafkaJsonSchemaSerde


application:
  configs:
    error.topic.name: error-topic