spring:
  cloud:
    stream:
      bindings:
        payment-request-channel:
          destination: payment_request
        payment-confirmation-channel:
          destination: payment_confirmation
      kafka:
        streams:
          binder:
            brokers:  localhost:9092
            configuration:
              commit.interval.ms: 10000
              state.dir: state-store
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          bindings:
            payment-request-channel:
              consumer:
                timestampExtractorBeanName: requestTimeExtractor
            payment-confirmation-channel:
              consumer:
                timestampExtractorBeanName: confirmationTimeExtractor

